services:
    armadillo:
        image: molgenis/molgenis-armadillo:latest
        ports:
            - 8080:8080
        volumes:
            - ./armadillo_home/config:/config
        depends_on:
            - default
    default:
        hostname: default
        image: datashield/rock_citest-permissive:latest
