#-------------------------------------------------------------------------------
# Copyright (c) 2019-2020 University of Newcastle upon Tyne. All rights reserved.
#
# This program and the accompanying materials
# are made available under the terms of the GNU Public License v3.0.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------

#
# Set up
#

context("ds.glmPredict::smk::setup")

connect.studies.dataset.cnsim(list("LAB_TSC", "LAB_TRIG", "DIS_AMI", "DIS_DIAB", "GENDER"))

test_that("setup", {
    ds_expect_variables(c("D"))
})

#
# Tests
#

context("ds.glmPredict::smk::gaussian")
test_that("simple glmPredict, gaussian, without newobj", {
    glmSLMA.res <- ds.glmSLMA('D$LAB_TSC~D$LAB_TRIG', family="gaussian", newobj="gaussian.glmslma.obj")

    expect_length(glmSLMA.res, 9)
    expect_equal(glmSLMA.res$num.valid.studies, 3)
    expect_length(glmSLMA.res$validity.check, 1)
    expect_equal(glmSLMA.res$validity.check, "<gaussian.glmslma.obj> appears valid in all sources")

    res <- ds.glmPredict("gaussian.glmslma.obj", newdataname = NULL, output.type = "response", na.action = "na.pass", newobj="gaussian.glmslma.predict.obj")

    expect_length(res, 3)
    expect_equal(class(res), "list")

    expect_length(res$sim1, 1)
    expect_length(res$sim1$safe.list, 10)
    expect_equal(class(res$sim1$safe.list), "list")
    expect_equal(res$sim1$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim1$safe.list$newdfname))
    expect_equal(res$sim1$safe.list$output.type, "response")
    expect_true(is.null(res$sim1$safe.list$dispersion))
    expect_equal(res$sim1$safe.list$fit.Ntotal, 1801)
    expect_equal(res$sim1$safe.list$fit.Nvalid, 1801)
    expect_equal(res$sim1$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim1$safe.list$fit.mean, 5.872024, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.sd, 0.3719756, tolerance = 1e-7)
    expect_length(res$sim1$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim1$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim1$safe.list$fit.quantiles[[1]], 5.656127, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[2]], 5.703222, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[3]], 5.778930, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[4]], 5.873137, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[5]], 5.961123, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[6]], 6.044376, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[7]], 6.091611, tolerance = 1e-7)

    expect_length(res$sim2, 1)
    expect_length(res$sim2$safe.list, 10)
    expect_equal(class(res$sim2$safe.list), "list")
    expect_equal(res$sim2$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim2$safe.list$newdfname))
    expect_equal(res$sim2$safe.list$output.type, "response")
    expect_true(is.null(res$sim2$safe.list$dispersion))
    expect_equal(res$sim2$safe.list$fit.Ntotal, 2526)
    expect_equal(res$sim2$safe.list$fit.Nvalid, 2526)
    expect_equal(res$sim2$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim2$safe.list$fit.mean, 5.843564, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.sd, 0.3027628, tolerance = 1e-7)
    expect_length(res$sim2$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim2$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim2$safe.list$fit.quantiles[[1]], 5.692873, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[2]], 5.725140, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[3]], 5.782866, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[4]], 5.843818, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[5]], 5.902650, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[6]], 5.958954, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[7]], 5.990324, tolerance = 1e-7)

    expect_length(res$sim3, 1)
    expect_length(res$sim3$safe.list, 10)
    expect_equal(class(res$sim3$safe.list), "list")
    expect_equal(res$sim3$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim3$safe.list$newdfname))
    expect_equal(res$sim3$safe.list$output.type, "response")
    expect_true(is.null(res$sim3$safe.list$dispersion))
    expect_equal(res$sim3$safe.list$fit.Ntotal, 3473)
    expect_equal(res$sim3$safe.list$fit.Nvalid, 3473)
    expect_equal(res$sim3$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim3$safe.list$fit.mean, 5.846405, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.sd, 0.3546622, tolerance = 1e-7)
    expect_length(res$sim3$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim3$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim3$safe.list$fit.quantiles[[1]], 5.639923, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[2]], 5.692488, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[3]], 5.763677, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[4]], 5.845627, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[5]], 5.928798, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[6]], 6.004785, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[7]], 6.054574, tolerance = 1e-7)
})

test_that("simple glmPredict, gaussian", {
    glmSLMA.res <- ds.glmSLMA('D$LAB_TSC~D$LAB_TRIG', family="gaussian", newobj="gaussian.glmslma.obj")

    expect_length(glmSLMA.res, 9)
    expect_equal(glmSLMA.res$num.valid.studies, 3)
    expect_length(glmSLMA.res$validity.check, 1)
    expect_equal(glmSLMA.res$validity.check, "<gaussian.glmslma.obj> appears valid in all sources")

    res <- ds.glmPredict("gaussian.glmslma.obj", output.type = "response", newobj="gaussian.glm.predict.obj")

    expect_length(res, 3)
    expect_equal(class(res), "list")

    expect_length(res$sim1, 1)
    expect_length(res$sim1$safe.list, 10)
    expect_equal(class(res$sim1$safe.list), "list")
    expect_equal(res$sim1$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim1$safe.list$newdfname))
    expect_equal(res$sim1$safe.list$output.type, "response")
    expect_true(is.null(res$sim1$safe.list$dispersion))
    expect_equal(res$sim1$safe.list$fit.Ntotal, 1801)
    expect_equal(res$sim1$safe.list$fit.Nvalid, 1801)
    expect_equal(res$sim1$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim1$safe.list$fit.mean, 5.872024, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.sd, 0.3719756, tolerance = 1e-7)
    expect_length(res$sim1$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim1$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim1$safe.list$fit.quantiles[[1]], 5.656127, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[2]], 5.703222, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[3]], 5.778930, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[4]], 5.873137, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[5]], 5.961123, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[6]], 6.044376, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[7]], 6.091611, tolerance = 1e-7)

    expect_length(res$sim2, 1)
    expect_length(res$sim2$safe.list, 10)
    expect_equal(class(res$sim2$safe.list), "list")
    expect_equal(res$sim2$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim2$safe.list$newdfname))
    expect_equal(res$sim2$safe.list$output.type, "response")
    expect_true(is.null(res$sim2$safe.list$dispersion))
    expect_equal(res$sim2$safe.list$fit.Ntotal, 2526)
    expect_equal(res$sim2$safe.list$fit.Nvalid, 2526)
    expect_equal(res$sim2$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim2$safe.list$fit.mean, 5.843564, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.sd, 0.3027628, tolerance = 1e-7)
    expect_length(res$sim2$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim2$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim2$safe.list$fit.quantiles[[1]], 5.692873, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[2]], 5.725140, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[3]], 5.782866, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[4]], 5.843818, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[5]], 5.902650, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[6]], 5.958954, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[7]], 5.990324, tolerance = 1e-7)

    expect_length(res$sim3, 1)
    expect_length(res$sim3$safe.list, 10)
    expect_equal(class(res$sim3$safe.list), "list")
    expect_equal(res$sim3$safe.list$glm.object, "gaussian.glmslma.obj")
    expect_true(is.null(res$sim3$safe.list$newdfname))
    expect_equal(res$sim3$safe.list$output.type, "response")
    expect_true(is.null(res$sim3$safe.list$dispersion))
    expect_equal(res$sim3$safe.list$fit.Ntotal, 3473)
    expect_equal(res$sim3$safe.list$fit.Nvalid, 3473)
    expect_equal(res$sim3$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim3$safe.list$fit.mean, 5.846405, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.sd, 0.3546622, tolerance = 1e-7)
    expect_length(res$sim3$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim3$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim3$safe.list$fit.quantiles[[1]], 5.639923, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[2]], 5.692488, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[3]], 5.763677, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[4]], 5.845627, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[5]], 5.928798, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[6]], 6.004785, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[7]], 6.054574, tolerance = 1e-7)
})

context("ds.glmPredict::smk::poisson")
test_that("simple glmPredict, poisson, without newobj", {
    glmSLMA.res <- ds.glmSLMA('D$LAB_TSC~D$LAB_TRIG', family="poisson", newobj="poisson.glmslma.obj")

    expect_length(glmSLMA.res, 9)
    expect_equal(glmSLMA.res$num.valid.studies, 3)
    expect_length(glmSLMA.res$validity.check, 1)
    expect_equal(glmSLMA.res$validity.check, "<poisson.glmslma.obj> appears valid in all sources")

    res <- ds.glmPredict("poisson.glmslma.obj", output.type = "response")

    expect_length(res, 3)
    expect_equal(class(res), "list")

    expect_length(res$sim1, 1)
    expect_length(res$sim1$safe.list, 10)
    expect_equal(class(res$sim1$safe.list), "list")
    expect_equal(res$sim1$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim1$safe.list$newdfname))
    expect_equal(res$sim1$safe.list$output.type, "response")
    expect_true(is.null(res$sim1$safe.list$dispersion))
    expect_equal(res$sim1$safe.list$fit.Ntotal, 1801)
    expect_equal(res$sim1$safe.list$fit.Nvalid, 1801)
    expect_equal(res$sim1$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim1$safe.list$fit.mean, 5.872024, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.sd, 0.3720242, tolerance = 1e-7)
    expect_length(res$sim1$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim1$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim1$safe.list$fit.quantiles[[1]], 5.659318, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[2]], 5.704707, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[3]], 5.778435, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[4]], 5.871512, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[5]], 5.959795, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[6]], 6.044552, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[7]], 6.093175, tolerance = 1e-7)

    expect_length(res$sim2, 1)
    expect_length(res$sim2$safe.list, 10)
    expect_equal(class(res$sim2$safe.list), "list")
    expect_equal(res$sim2$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim2$safe.list$newdfname))
    expect_equal(res$sim2$safe.list$output.type, "response")
    expect_true(is.null(res$sim2$safe.list$dispersion))
    expect_equal(res$sim2$safe.list$fit.Ntotal, 2526)
    expect_equal(res$sim2$safe.list$fit.Nvalid, 2526)
    expect_equal(res$sim2$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim2$safe.list$fit.mean, 5.843564, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.sd, 0.3027769, tolerance = 1e-7)
    expect_length(res$sim2$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim2$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim2$safe.list$fit.quantiles[[1]], 5.694361, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[2]], 5.725835, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[3]], 5.782577, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[4]], 5.843101, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[5]], 5.902120, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[6]], 5.959162, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[7]], 5.991181, tolerance = 1e-7)

    expect_length(res$sim3, 1)
    expect_length(res$sim3$safe.list, 10)
    expect_equal(class(res$sim3$safe.list), "list")
    expect_equal(res$sim3$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim3$safe.list$newdfname))
    expect_equal(res$sim3$safe.list$output.type, "response")
    expect_true(is.null(res$sim3$safe.list$dispersion))
    expect_equal(res$sim3$safe.list$fit.Ntotal, 3473)
    expect_equal(res$sim3$safe.list$fit.Nvalid, 3473)
    expect_equal(res$sim3$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim3$safe.list$fit.mean, 5.846405, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.sd, 0.3546933, tolerance = 1e-7)
    expect_length(res$sim3$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim3$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim3$safe.list$fit.quantiles[[1]], 5.642464, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[2]], 5.693362, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[3]], 5.763027, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[4]], 5.844277, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[5]], 5.927911, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[6]], 6.005366, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[7]], 6.056664, tolerance = 1e-7)
})

test_that("simple glmPredict, poisson", {
    glmSLMA.res <- ds.glmSLMA('D$LAB_TSC~D$LAB_TRIG', family="poisson", newobj="poisson.glmslma.obj")

    expect_length(glmSLMA.res, 9)
    expect_equal(glmSLMA.res$num.valid.studies, 3)
    expect_length(glmSLMA.res$validity.check, 1)
    expect_equal(glmSLMA.res$validity.check, "<poisson.glmslma.obj> appears valid in all sources")

    res <- ds.glmPredict("poisson.glmslma.obj", output.type = "response", newobj="poisson.glm.predict.obj")

    expect_length(res, 3)
    expect_equal(class(res), "list")

    expect_length(res$sim1, 1)
    expect_length(res$sim1$safe.list, 10)
    expect_equal(class(res$sim1$safe.list), "list")
    expect_equal(res$sim1$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim1$safe.list$newdfname))
    expect_equal(res$sim1$safe.list$output.type, "response")
    expect_true(is.null(res$sim1$safe.list$dispersion))
    expect_equal(res$sim1$safe.list$fit.Ntotal, 1801)
    expect_equal(res$sim1$safe.list$fit.Nvalid, 1801)
    expect_equal(res$sim1$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim1$safe.list$fit.mean, 5.872024, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.sd, 0.3720242, tolerance = 1e-7)
    expect_length(res$sim1$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim1$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim1$safe.list$fit.quantiles[[1]], 5.659318, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[2]], 5.704707, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[3]], 5.778435, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[4]], 5.871512, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[5]], 5.959795, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[6]], 6.044552, tolerance = 1e-7)
    expect_equal(res$sim1$safe.list$fit.quantiles[[7]], 6.093175, tolerance = 1e-7)

    expect_length(res$sim2, 1)
    expect_length(res$sim2$safe.list, 10)
    expect_equal(class(res$sim2$safe.list), "list")
    expect_equal(res$sim2$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim2$safe.list$newdfname))
    expect_equal(res$sim2$safe.list$output.type, "response")
    expect_true(is.null(res$sim2$safe.list$dispersion))
    expect_equal(res$sim2$safe.list$fit.Ntotal, 2526)
    expect_equal(res$sim2$safe.list$fit.Nvalid, 2526)
    expect_equal(res$sim2$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim2$safe.list$fit.mean, 5.843564, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.sd, 0.3027769, tolerance = 1e-7)
    expect_length(res$sim2$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim2$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim2$safe.list$fit.quantiles[[1]], 5.694361, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[2]], 5.725835, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[3]], 5.782577, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[4]], 5.843101, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[5]], 5.902120, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[6]], 5.959162, tolerance = 1e-7)
    expect_equal(res$sim2$safe.list$fit.quantiles[[7]], 5.991181, tolerance = 1e-7)

    expect_length(res$sim3, 1)
    expect_length(res$sim3$safe.list, 10)
    expect_equal(class(res$sim3$safe.list), "list")
    expect_equal(res$sim3$safe.list$glm.object, "poisson.glmslma.obj")
    expect_true(is.null(res$sim3$safe.list$newdfname))
    expect_equal(res$sim3$safe.list$output.type, "response")
    expect_true(is.null(res$sim3$safe.list$dispersion))
    expect_equal(res$sim3$safe.list$fit.Ntotal, 3473)
    expect_equal(res$sim3$safe.list$fit.Nvalid, 3473)
    expect_equal(res$sim3$safe.list$fit.Nmiss, 0)
    expect_equal(res$sim3$safe.list$fit.mean, 5.846405, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.sd, 0.3546933, tolerance = 1e-7)
    expect_length(res$sim3$safe.list$fit.quantiles, 7)
    expect_equal(class(res$sim3$safe.list$fit.quantiles), "numeric")
    expect_equal(res$sim3$safe.list$fit.quantiles[[1]], 5.642464, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[2]], 5.693362, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[3]], 5.763027, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[4]], 5.844277, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[5]], 5.927911, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[6]], 6.005366, tolerance = 1e-7)
    expect_equal(res$sim3$safe.list$fit.quantiles[[7]], 6.056664, tolerance = 1e-7)
})

#
# Shutdown
#

context("ds.glmPredict::smk::shutdown")

test_that("shutdown", {
    ds_expect_variables(c("D", "gaussian.glmslma.obj", "gaussian.glmslma.predict.obj", "gaussian.glm.predict.obj","poisson.glm.predict.obj", "poisson.glmslma.obj", "predict_glm"))
})

disconnect.studies.dataset.cnsim()

#
# Done
#

context("ds.glmPredict::smk::done")
