#' 
#' @title generates a message for the user after an assign function is ran
#' @description this is an internal function called by some client functions.
#' @details the function verifies the output of the assign function and displays a
#' message telling the user whether the expected output has been produced.
#' @param obj the name of the object generated by the assign function.
#' @return a message
#' @author Gaye, A.
#'
.tellUser <- function(datasources=NULL, obj=NULL){
  # names of the data sources (studies)
  stdnames <- names(datasources)
  
  # variable to return
  output <- rep(1, length(stdnames))
  
  qc <- ds.exists(datasources, obj)
  indx <- as.numeric(which(qc==TRUE))
  if(length(indx) == length(datasources)){
    message("The output of the function, '", obj, "', is stored on the server side.")
  }else{
    if(length(indx) > 0){
      output[indx] <- 1
      warning(paste0("The output object, '", obj, "', was generated only for ", names(datasources)[indx], "!"), call.=FALSE)
    }
    if(length(indx) == 0){
      output <- rep(0, length(stdnames))
      warning("The output object has not been generated for any of the studies!", call.=FALSE)
    }
  }
  
  return(output)
}