################################################################################
# DataSHIELD GHA test suite - dsBaseClient
# Adapted from `azure-pipelines.yml` by Roberto Villegas-Diaz
#
# Inside the root directory $(Pipeline.Workspace) will be a file tree like:
# /dsBaseClient               <- Checked out version of datashield/dsBaseClient
# /dsBaseClient/logs          <- Where results of tests and logs are collated
# /testStatus           <- Checked out version of datashield/testStatus
#
# As of Jul 2025 this takes ~ 9 mins to run.
################################################################################
name: dsBaseClient tests' suite

on:
  push:
  schedule:
    - cron: '0 0 * * 0'   # Weekly
    - cron: '0 1 * * *'   # Nightly

jobs:
  dsBaseClient_test_suite:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: write
    
    # These should all be constant, except TEST_FILTER. This can be used to test 
    # subsets of test files in the testthat directory. Options are like:
    # '*'               <- Run all tests.
    # 'asNumericDS*'    <- Run all asNumericDS tests, i.e. all the arg, etc. tests.
    # '*_smk_*'         <- Run all the smoke tests for all functions.
    env:
      TEST_FILTER: '*'
      _r_check_system_clock_: 0
      WORKFLOW_ID: ${{ github.run_id }}-${{ github.run_attempt }}
      PROJECT_NAME: dsBase
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      REPO_OWNER: ${{ github.repository_owner }}
      R_KEEP_PKG_SOURCE: yes
      GITHUB_TOKEN: ${{ github.token || 'placeholder-token' }}

    steps:
      - name: Checkout dsBaseClient
        uses: actions/checkout@v4
        with:
          path: dsBaseClient

      - name: Checkout testStatus
        if: ${{ github.actor != 'nektos/act' }} # for local deployment only
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_OWNER }}/testStatus
          ref: master
          path: testStatus
          persist-credentials: false
          token: ${{ env.GITHUB_TOKEN }}
          
      - name: Uninstall default MySQL
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          sudo service mysql stop || true
          sudo apt-get update
          sudo apt-get remove --purge mysql-client mysql-server mysql-common -y
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo rm -rf /var/lib/mysql/
          
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: release
          use-public-rspm: true
          
      # - name: Install dsBaseClient dependencies
      #   run: |
      #     sudo Rscript -e "install.packages(c('devtools','covr','fields','meta','metafor','ggplot2','gridExtra','data.table','DSI','DSOpal','DSLite','MolgenisAuth','MolgenisArmadillo','DSMolgenisArmadillo','DescTools','e1071'), repos='https://cloud.r-project.org')"
      #     sudo Rscript -e "devtools::install_github(repo='datashield/dsDangerClient', ref=Sys.getenv('BRANCH_NAME'))"
      #     # R CMD INSTALL ./dsBaseClient

      - name: Install R and dependencies
        run: |
          sudo apt-get install --no-install-recommends software-properties-common dirmngr -y
          wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
          sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
          sudo apt-get update -qq
          sudo apt-get upgrade -y
          sudo apt-get install -qq libxml2-dev libcurl4-openssl-dev libssl-dev libgsl-dev libgit2-dev r-base -y
          sudo apt-get install -qq libharfbuzz-dev libfribidi-dev libmagick++-dev xml-twig-tools -y
          sudo R -q -e "install.packages(c('devtools','covr','fields','meta','metafor','ggplot2','gridExtra','data.table','DSI','DSOpal','DSLite','MolgenisAuth','MolgenisArmadillo','DSMolgenisArmadillo','DescTools','e1071'), repos='https://cloud.r-project.org')"
          sudo R -q -e "devtools::install_github(repo='datashield/dsDangerClient', ref=Sys.getenv('BRANCH_NAME'))"

      - name: Check manual updated
        run: |
          orig_sum=$(find man -type f | sort -u | xargs cat | md5sum)
          R -q -e "devtools::document()"
          new_sum=$(find man -type f | sort -u | xargs cat | md5sum)
          if [ "$orig_sum" != "$new_sum" ]; then
            echo "Your committed man/*.Rd files are out of sync with the R headers."
            exit 1
          fi
        working-directory: dsBaseClient
        continue-on-error: true

      - name: Devtools checks
        run: |
          R -q -e "devtools::check(args = c('--no-examples', '--no-tests'))" | tee azure-pipelines_check.Rout
          grep --quiet "^0 errors" azure-pipelines_check.Rout && grep --quiet " 0 warnings" azure-pipelines_check.Rout && grep --quiet " 0 notes" azure-pipelines_check.Rout
        working-directory: dsBaseClient
        continue-on-error: true
        
      - name: Start Armadillo docker-compose
        run: docker compose -f docker-compose_armadillo.yml up -d --build
        working-directory: dsBaseClient

      - name: Install test datasets
        run: |
          sleep 60
          R -q -f "molgenis_armadillo-upload_testing_datasets.R"
        working-directory: dsBaseClient/tests/testthat/data_files

      - name: Install dsBase to Armadillo
        run: |
          curl -u admin:admin -X GET http://localhost:8080/packages
          curl -u admin:admin -H 'Content-Type: multipart/form-data' -F "file=@dsBase_6.3.4-permissive.tar.gz" -X POST http://localhost:8080/install-package
          sleep 60
          docker restart dsbaseclient-armadillo-1
          sleep 30
          curl -u admin:admin -X POST http://localhost:8080/whitelist/dsBase
        working-directory: dsBaseClient
